### ISSUE TITLE
VolumeMeter

### ISSUE THREAD

**Issue by drwells** [drwells/fiddle#192]
We need averages over spheres for some features in the new heart model: the easiest way to do this would be to have another class which is like `SurfaceMeter` but for codim 0 meshes.

**Comment by marshallrdavey** [comment]
A pressure focused version is included in `four-chambered-heart`
https://github.com/IBAMR/four-chambered-heart/blob/979609926d20e4043a6f666bee08591ccbca396e/source/SourceDistributer.cpp#L130

For the fluid sources or pressure meters, it would be helpful if this class worked similarly to `SurfaceMeter` in that it can update it's location as well as scalar averaging for a given SAMRAI `data_index`
