### ISSUE TITLE
Implement basic fiber field support.

### ISSUE THREAD

**Issue by drwells** [drwells/fiddle#3]
Holzapfel-Ogden is dependent completely on the invariants.

Try looking at MechanicsModel.cpp in the heart model.

For Fung-type models: we have three fiber fields and take a cross product, and then we have to do things in different orientations - take a look at MechanicsModel.h.

**Comment by drwells** [comment]
@marshallrdavey I think we have enough stuff (particularly with #50) to implement this in a useful way. I am content to merge #50 as-is if it is enough to get started with fibers.

We presently store fibers in ExodusII files with one value per cell. What do we do once we load all three vectors? It would help me to implement something generic if I better understood the next few steps.

**Comment by marshallrdavey** [comment]
We copy them into a system object (https://github.com/IBAMR/four-chambered-heart/blob/08d273df3c4b993213f6f30b7d2244e3df6cda2e/source/ModelInitialization.cpp#L167)  that is handed to a SystemData object owned by the stress function.

**Comment by drwells** [comment]
OK, so we always use elemental data. I think I can implement a version of this that uses only cell-level data (i.e., no `DoFHandler`) here fairly easily.

**Comment by drwells** [comment]
Is there anything preventing us from using a higher-order finite element field description of the fibers?

**Comment by drwells** [comment]
@marshallrdavey now that we have the ExodusII readers it makes sense to start thinking about how we want to load in model fiber data. Are you willing to try and write a fiber-reinforced class? We should start by using one fiber vector per active cell (same as IBAMR).

**Comment by marshallrdavey** [comment]
@drwells do you want a specific fiber reinforced class? I was thinking that the fibers could just be passed into a `ElasticForce` derivative like `MaterialModel` where the `MaterialModel` class stores the fiber field and accesses it when needed for the stress calculations as it does with the spring constant `alpha`

**Comment by drwells** [comment]
I think at this point any model will do - lets just use the simplest one and we can generalize later.

Would that approach work with the rest of the infrastructure? Whatever we do it should be compatible with the rest of the force calculation functions.

**Comment by marshallrdavey** [comment]
We can use the `const typename Triangulation<dim>::active_cell_iterator & /*cell*/` that is already in `compute_stress` to access the cell specific data as long as the numbering is the same. The `ElasticForce` class is not a part of `fiddle` however.

**Comment by marshallrdavey** [comment]
I have an exodus file of a plain cylinder I can build an example out of. The example could include a single fiber family of anisotropy with a pressure load applied uniformly to the inside of the cylinder.

**Comment by drwells** [comment]
We can always use `active_cell_index()` to access cell data. That's how we load per-cell data from ExodusII too.

> I have an exodus file of a plain cylinder I can build an example out of. The example could include a single fiber family of anisotropy with a pressure load applied uniformly to the inside of the cylinder.

We can do that but I recommend starting by writing the force function that uses fibers first. We can check that that works with MMS.

**Comment by marshallrdavey** [comment]
I'm not sure what you want this to look like. Do you just want me to define a generic material model class that takes a fiber vector as a constructor argument in `project-dlm` ? Or do we need to rewrite `implicit_mechanics` so the `ForceContributions` are externally passed into the class, and then write an example using fibers?

**Comment by drwells** [comment]
> I'm not sure what you want this to look like. 

Me neither - I think that if we write a `ForceContribution` that works with fibers that will provide sufficient guidance on what to try next.

> Do you just want me to define a generic material model class that takes a fiber vector as a constructor argument in project-dlm ?

Lets do the explicit version first so we can see how all the pieces work.


>  Or do we need to rewrite implicit_mechanics so the ForceContributions are externally passed into the class, and then write an example using fibers?

we need to do that anyway for other reasons unrelated to fibers.

**Comment by drwells** [comment]
@labdala This is part of what we talked about this morning. Before we put these things in a force function, we should implement something like

```cpp
template <int dim, int spacedim = dim>
class FiberNetwork
{
public:
    FiberNetwork(const Triangulation<dim, spacedim> &tria,
                 const std::string &exodus_filename,
                 const std::array<int, dim> &fiber_ids);

    FiberNetwork(const Triangulation<dim, spacedim> &tria,
                 const std::vector<Tensor<1, dim>> fibers);


    Tensor<1, dim>
    get_fiber(typename Triangulation<dim, spacedim>::active_cell_iterator &cell) const;
};
```
to store cell-centered fiber network data. Do we always have `dim` fiber networks? If so we should modify this slightly to put all three in one of these objects.

**Comment by drwells** [comment]
Some more hints for you:
1. This class may want to store a `dealii::SmartPointer` pointing to the `Triangulation` for future use.
2. We need an indexing scheme that translates `cell->active_cell_index()` into a locally contiguous index space. See if you can figure this out from the documentation.
3. we need some tests of course

**Comment by marshallrdavey** [comment]
@drwells we have various size fiber networks. `get_fiber` could return an array/vector of `Tensor<1, dim>` with the size established/stored by `FiberNetwork`. Elements in the same part should have the same number of fiber fields.

**Comment by drwells** [comment]
that could also work - I don't know whether it is better to have multiple `FiberNetwork`s or one `FiberNetwork` which stores several vectors per cell. If we always use all vectors at the same place then the second one is probably more convenient.

**Comment by marshallrdavey** [comment]
I think the latter is more useful for us because multiple fiber systems are usually needed for the passive mechanics. It is similarly useful to have access to all of them for the active mechanics as well in certain cases.

**Comment by drwells** [comment]
With all that in mind lets do something like

```cpp
template <int dim, int spacedim = dim>
class FiberNetwork
{
public:
    FiberNetwork(const Triangulation<dim, spacedim> &tria,
                 const std::string &exodus_filename,
                 const std::vector<int> &fiber_ids);

    FiberNetwork(const Triangulation<dim, spacedim> &tria,
                 const std::vector<std::vector<Tensor<1, dim>>> &fibers);


    const ArrayView<Tensor<1, dim>> &
    get_fibers(typename Triangulation<dim, spacedim>::active_cell_iterator &cell) const;

private:
    Table<2, Tensor<1, dim>> fibers;
};
```
to store and return a variable number of fiber fields per cell. @labdala want to give this a try?

**Comment by labdala** [comment]
Yes! Thanks for the outline @drwells !

**Comment by drwells** [comment]
@labdala Any progress? If things work in serial then we should merge that first and work on parallelization second.

**Comment by labdala** [comment]
Yes, I made progress but have had some technical difficulties with my trilinos+dealii+ibamr set up. Now everything is fixed. I am working on the example/test and will create a PR soon.

**Comment by labdala** [comment]
@drwells can you give me permission to push a branch upstream?

**Comment by drwells** [comment]
Could you fork this repo instead?

**Comment by drwells** [comment]
Fixed by some other fiber-related PRs: loading in the data works and the basic data structures also work so lets close.
